CREATE TABLE IF NOT EXISTS links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT UNIQUE NOT NULL,
  origin TEXT NOT NULL,
  visit INTEGER NOT NULL DEFAULT 0,
  created INTEGER NOT NULL,
  secret TEXT NOT NULL
);